### PR TITLE
Gameplay sanity cleanup

### PR DESCRIPTION
**Pull request by Wuzzy2**
I've implemented all the stuff I discussed here:

https://forum.minetest.net/viewtopic.php?f=10&t=12156&start=75#p183781

Mostly this removes some of the “insanities” in the gameplay, like being able to craft (and thus build) fences and locked chests, some bows being uncraftable, changing or removing stuff which does not really belong in this game, etc.

Please also follow the discussion; I want to have this discussed before this becomes an actual part of Hungry Games.

NOTE: Before you merge this, you probably need to clean up the map on your server and remove the locked chests and other werid stuff with WorldEdit.
This PR includes an alias from default:chest_locked to default:chest, but it won't get rid of the formspec and the (faulty) infotext indicating ownership. The locked chests won't work after this, however.

### CODE REVIEW

**Comment by GunshipPenguin** [comment]
While I like most of these changes, I'm hesitant to modify too heavily mods that are included with minetest_game. My problem is this: the version of minetest_game that this subgame is based off of is quite old and as a result, several textures, sounds, items and functionalities are outdated or missing completely. I'd like to update the mods in this subgame that are a part of minetest_game and was planning on doing that after the next release of the minetest engine, using the version of minetest_game that has been tagged with the version number of the new release of minetest. When the mods in this subgame that are a part of minetest_game are modified however, it makes it difficult to update them and carry over the changes that were made to the older version. 

What do you think? If I were to merge this and then update the mods that are a part of minetest_game sometime in the future would it be difficult to carry over these changes? Or should I update the mods now and then we can try to implement these changes?

**Comment by Wuzzy2** [comment]
Of what “changes” are you talking about exactly (especially “functionalities”)? Are there specific features you want to have included in this subgame? My answer would depend on what from Minetest Game you would want.

As for textures and other media files, I think one simple copy should do the job. However, I don't like the idea of cloning Minetest's Game style so much.
Maybe we could look through the texture packs and use one of them instead?
But my feelings are not very strong about this; if you want to replace the textures that badly, go ahead. :P

I suppose the Minetest Game part in this subgame already has been modified heavily enough that an easy merge is _already_ probably not possible anymore, but I may be wrong.
But on the other hand, I personally don't care about original Minetest Game at all here. Also, I am worried that permanently eyeing towards Minetest Game could slow down progress; I am viewing Hungry Games as independent. Maybe it's better to just let go of Minetest Game. But that's just my 2 cents.

**Comment by GunshipPenguin** [comment]
I understand what you mean about permanently eyeing towards minetest_game slowing things down. Rest assured, I don't want to do that. I simply think that updating the minetest_game mods in this subgame just once would be beneficial, as the version of minetest_game that this subgame is based off of is quite old.

I've been trying to merge some mods from the latest minetest_game into this subgame today to gauge the difficulty of a merge. Just like you guessed, textures and sounds are trivial to merge, just a simple copy. In addition, code is not actually that hard to merge, the minetest_game mods in this subgame haven't actually been modified too heavily, and a merge is still completely doable in my mind. The only problem that I'm having is that the latest commit of minetest_game is incompatible with minetest-0.4.12 stable. This seems to be due to the fact that minetest-0.4.12 stable does not have support for raillike group names, as added in this commit - minetest/minetest@75622c30beb390b7ed578010a00390aa971b3951. I could merge in the version of minetest_game that was tagged 0.4.12, but since that tag, a few things have been added that I'd like to see included in hungry_games (Mese lamps, listrings and some other changes). 

So here's what I propose doing. Since this PR mainly just removes items and features in the minetest_game mods that interfere with hungry_games, I'll merge this PR. When the next stable version of minetest is released, I'll merge the mods from the tagged version of minetest_game into hungry_games and carry over the changes in this PR. Since the vast majority of this PR is to do with deleting unnecessary items/features, it shouldn't be too difficult.

What do you think of my solution?

**Comment by Wuzzy2** [comment]
Agreed.
If you run into problems later, feel free to contact me.

**Pull request merged**
