### PR TITLE
Wall fix and update snow mod

### PR DESCRIPTION
**Pull request by HybridDog**
@GunshipPenguin your server is unplayable, this should stop the wall node spreading
screenshot_20150814_142458

### CODE REVIEW

**Comment by GunshipPenguin** [comment]
The server is in its current state due to the fact that I've been away for 2 weeks and have been unable to access it during most of the time I've been away. I'm going to be returning tomorrow and will be fixing everything then.

When I return, I'm planning on updating all minetest_game mods to their latest versions and removing the snow mod, as snow biomes are now generated by default. This means that commit 4628fd9bd98b9eeefa835acd834d7414baef7088 is unnecessary. 

The one problem that you do fix here that I haven't heard of is the arena wall spreading around the map. Can you elaborate a bit on exactly why this is happening and what you do to solve it in commits 595070d970f821d16c6a0a3e13969acb2722bbd4 and ead8d57d3685f6cd57b3a76741e9b6d2c2b74edc?

**Comment by HybridDog** [comment]
on the server l somehow managed to get a wall_middle in my inventory
l placed it and… see the screenshot above
https://github.com/GunshipPenguin/hungry_games/blob/master/mods/glass_arena/init.lua#L100

**Comment by GunshipPenguin** [comment]
I'm currently looking into removing the glass_arena mod in favour of using map_generation_limit setting in minetest.conf instead to simply limit the mapgen to the size of the arena. That way, things will be much simpler, and it will be impossible for anybody to glitch outside of the arena.

If it turns out that that is not possible, I'll merge the commits in this PR pertaining to the glass_arena mod, but not the snow mod as it has now been removed.

**Comment by HybridDog** [comment]
ok

**Pull request closed without merging**
