### PR TITLE
add a shell script to automatically update some mods and use this script

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by GunshipPenguin** [comment]
I'm not really a fan of having a mod update script that has to be changed whenever a new mod is added to the subgame included. I do however like that this PR updates some of the mods included. 

I'm going to merge this, but will probably remove the script in the future, in favour of another solution to the problem of updating mods in this subgame. What I'd like to do ultimately is lessen the amount of mods included, making the subgame more lean, and lessening the problem of mod updates.

**Comment by HybridDog** [comment]
> I'm not really a fan of having a mod update script that has to be changed whenever a new mod is added to the subgame included

the script is actually just a simple one executing a few download commands
if a new mod becomes added, the script still works

> What I'd like to do ultimately is lessen the amount of mods included

it's a game, so l think e.g. the snow mod should not be loaded as part of this game but as a usual mod

**Comment by GunshipPenguin** [comment]
What I meant was that if you were to add a mod to this subgame and wanted it to be updated by the mod update script, you would have to edit the mod update script to make it download and install the new mod.

I agree with you comments on the snow mod, it's what I was mainly referring to when I said I wanted to lessen the amount of mods included, and I'll probably remove it from the subgame. I think that it's much more suited for use as a usual mod than a part of the subgame, especially seeing  as snow biomes will be generated by default with mgv6 in the next release of minetest.

**Comment by HybridDog** [comment]
> What I meant was that if you were to add a mod to this subgame and wanted it to be updated by the mod update script, you would have to edit the mod update script to make it download and install the new mod.

yes, but instead of downloading it manually, unzipping it and renaming it
you only need to add one line and run the script

> snow biomes will be generated by default with mgv6

but they look different

**Pull request merged**
